### PR TITLE
KECA-37: Include UUID in uuid_broadcast arguments

### PR DESCRIPTION
**Pull request by jamesaimonetti**

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
Reverts https://github.com/2600hz/kazoo-ecallmgr/commit/74f3389acad952d9c5e6bfbd44a36bff097fcf40#diff-e6ccc5773f98057122a3962e7110cd0b6a82d3ce7e98fb6d2afeaac8bd541c9eR1019
@lazedo thoughts on why no UUID? ecallmgr_util has a handler for "broadcast" but doesn't appear to include the UUID either.

**Comment by lazedo** [comment]
@jamesaimonetti its an app not a uuid call where did that uuid call in the ticket came from ?

**Comment by lazedo** [comment]
```
diff --git a/src/ecallmgr_util.erl b/src/ecallmgr_util.erl
index b810ed2..841ce07 100644
--- a/src/ecallmgr_util.erl
+++ b/src/ecallmgr_util.erl
@@ -173,7 +173,8 @@ send_cmd(Node, UUID, App, "playseek", Cmd) ->
 send_cmd(Node, UUID, App, "unbridge", _) ->
     lager:debug("execute on node ~s: ~s uuid_park(~s)", [Node, App, UUID]),
     freeswitch:api(Node, 'uuid_park', UUID);
-send_cmd(Node, _UUID, App, "broadcast", Args) ->
+send_cmd(Node, UUID, App, "broadcast", BroadcastArgs) ->
+    Args = iolist_to_binary([UUID, " ", BroadcastArgs]),
     lager:debug("execute on node ~s: ~s uuid_broadcast(~s)", [Node, App, Args]),
     Resp = freeswitch:api(Node, 'uuid_broadcast', iolist_to_binary(Args)),
     lager:debug("broadcast resulted in: ~p", [Resp]),
```

try this one instead.
call_cmd should return apps, ecallmgr_util:send/5 can override the app and do a uuid_call instead

**Comment by lazedo** [comment]
another alternative is to remove the fun clause and let it run the `broadcast` app on freeswitch

**Comment by lazedo** [comment]
fixed with https://github.com/2600hz/kazoo-ecallmgr/commit/9dd6acbf132e20f6d929466033e80b9ad65ce299 instead

**Pull request closed without merging**
