### PR TITLE
Tag destroyed channels to avoid ghosts

### PR DESCRIPTION
**Pull request by jamesaimonetti**
When a CHANNEL_CREATE is followed by a CHANNEL_DESTROY within the time
the channel is being authz_req'd and route_req'd, the CHANNEL_DESTROY
clears the channels cache entry, and the authz process re-inserts it.

This issue is similar in nature to #42

So to counter it, tag destroyed channels entries with their
timestamp (in milliseconds) and avoid selecting channels that have the
destroyed_ms property set.

Add additional cleanup pass to remove destroyed channels.

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
Schema updates here: https://github.com/2600hz/kazoo-crossbar/pull/138

**Comment by lazedo** [comment]
@jamesaimonetti `and the authz process re-inserts it`, i would prefer to look into why we are adding the channel besides the channel_create or the channel_sync and fix it there

**Comment by jamesaimonetti** [comment]
@lazedo thought about that; my counter is that we partially solved this by the fix for the CHANNEL_UPDATE coming in, thought we were good, then this authz one popped into the queue. This PR should address any event coming into ecallmgr_fs_channels that might create a ghost record after CHANNEL_DESTROY. We can also look for the individual events but I don't know how you differentiate `no record exists because it hasn't been create` vs `no record exists because CHANNEL_DESTROY removed it`. This helps us differentiate.

**Comment by lazedo** [comment]
i would prefer to change fs_channels to only create on `channel_create` or `channel_sync`.

**Comment by jamesaimonetti** [comment]
@lazedo see #70  as alternative

**Pull request closed without merging**
