### PR TITLE
Rename function

### PR DESCRIPTION
**Pull request by harenson**
This function was renamed on this PR https://github.com/2600hz/kazoo-core/pull/9 and this (ecallmgr) PR needs to be merged before that one so it can pass CI checks.

This PR won't pass CI `kazoo/code-checks` check because it lacks the change from the PR previously mentioned.

### CODE REVIEW

**Comment by lazedo** [comment]
the fix should be done in the core pr. why the rename in that pr ?

**Comment by harenson** [comment]
@lazedo The rename was to match the convention with the other functions, so the event name was `conference_error` so the publish function "should" be named `publish_conference_error` that way you know it is for the `conference_error` event ;)

*the fix should be done in the core pr* I don't understand what do you mean by this.

**Comment by lazedo** [comment]
`the fix should be done in the core pr I don't understand what do you mean by this.` means you should `undo` the rename in the core pr

**Comment by harenson** [comment]
Why? It was breaking the naming style on that module.

**Comment by lazedo** [comment]
i'm more concerned in breaking other people code. the why of style was commented on that pr

**Pull request closed without merging**
