### PR TITLE
PISTON-1184: Correctly escape and wrap values when passing to FS to prevent special characters from causing issues

### PR DESCRIPTION
**Pull request by bradfordben**

### CODE REVIEW

**Comment by bradfordben** [comment]
4.3 PR: https://github.com/2600hz/kazoo/pull/6706

**Comment by bradfordben** [comment]
@jamesaimonetti for some reason your circel ci is returning unauthorized when it was working before 🤷 

I can not build locally as kazoo5 build process is also failing. 
```make[2]: Entering directory '/usr/local/src/kazoo5/deps/amqp_dist'
 DEPEND amqp_dist.d
 ERLC   amqp_dist.erl amqp_dist_acceptor.erl amqp_dist_node.erl
src/amqp_dist.hrl:2: can't find include lib "kernel/include/logger.hrl"
src/amqp_dist.erl:201: field f_handshake_complete undefined in record hs_data
src/amqp_dist.erl:292: Warning: function handshake_complete_fun/0 is unused
/usr/local/src/kazoo5/erlang.mk:5441: recipe for target 'ebin/amqp_dist.app' failed
make[3]: *** [ebin/amqp_dist.app] Error 1
/usr/local/src/kazoo5/erlang.mk:5183: recipe for target 'app' failed
make[2]: *** [app] Error 2
make[2]: Leaving directory '/usr/local/src/kazoo5/deps/amqp_dist'
../erlang.mk:4512: recipe for target 'deps' failed
make[1]: *** [deps] Error 2
make[1]: Leaving directory '/usr/local/src/kazoo5/deps'
Makefile:233: recipe for target '/usr/local/src/kazoo5/make/.deps.mk.cf230983a33e1d720979852f3281d793' failed
make: *** [/usr/local/src/kazoo5/make/.deps.mk.cf230983a33e1d720979852f3281d793] Error 2
[root@vm01 kazoo5]#
[root@vm01 kazoo5]#
[root@vm01 kazoo5]# cd applications/ecallmgr/
[root@vm01 ecallmgr]# make
make[1]: Entering directory '/usr/local/src/kazoo5'
make[1]: Nothing to be done for 'apps-makefile'.
make[1]: Leaving directory '/usr/local/src/kazoo5'
/usr/local/src/kazoo5/make/kz.mk:173: recipe for target '.test.deps' failed
make: *** [.test.deps] Error 127
[root@vm01 ecallmgr]#```

**Comment by bradfordben** [comment]
Updated eunit tests and rebased off master

**Comment by jamesaimonetti** [comment]
LGTM

**Pull request merged**
